[alias]
lint = "run --bin linter all"
e2e-complete = "run --bin e2e-complete-workflow-tests"
e2e-infrastructure = "run --bin e2e-infrastructure-lifecycle-tests"
e2e-deployment = "run --bin e2e-deployment-workflow-tests"
cov = "llvm-cov"
cov-check = "llvm-cov --all-features --workspace --fail-under-lines 70"
cov-lcov = "llvm-cov --lcov --output-path=./.coverage/lcov.info"
cov-codecov = "llvm-cov --codecov --output-path=./.coverage/codecov.json"
cov-html = "llvm-cov --html"
time = "build --timings --all-targets"

[build]
rustflags = [
  "-D",
  "warnings",
  "-D",
  "future-incompatible",
  "-D",
  "let-underscore",
  "-D",
  "nonstandard-style",
  "-D",
  "rust-2018-compatibility",
  "-D",
  "rust-2018-idioms",
  "-D",
  "rust-2021-compatibility",
  "-D",
  "unused",
]
